	cout<<"benvenuto nella sezione shop!!";
	cout<<"\n===========================================================================";
	cout<<"\n|$DOLLARSIDE$---->shop                                                    |";
	cout<<"\n|*************************************************************************|";
	cout<<"\n|_______________le nostre cards___________________________________________|";
	cout<<"\n|bronze card                     | platinum card| gold card       |";
	cout<<"\n| hai una prova gratuita         |              |                 |       |";
	cout<<"\n| sulla sezione traders          |                      |";
	cout<<"\n|                                |                                ";
	cout<<"\n|                                |                    |";
	cout<<"\n|                                |                                         |";
	cout<<"\n|                                |                                         |";
	cout<<"\n|                                |                                         |";
	cout<<"\n|                                |                                         |";
	cout<<"\n|                                |                                         |";
	cout<<"\n|                                |                                         |";
	cout<<"\n| costo=50$                      |                                         |";
	cout<<"\n|*************************************************************************|";	
	cout<<"\n|  guadagno stimato--->20%                     costo=15% del guadagno     |";
	cout<<"\n===========================================================================\n\n\n";
	return 0;
